mysql:
  image: mysql:5
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=docker
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
  ports:
    - "3306:3306"
  volumes:
    - .:/root/host

php:
  build: myphp
  ports:
    - "80:80"
  volumes:
    - .:/var/www
  links:
    - "mysql"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:db"